### ISSUE TITLE
How to Build Question

### ISSUE THREAD

**Issue by SilentProwler** [andrewzeng/Codex-Fanfiction#1]
Okay, so I was planning on trying to use this to upgrade certain things (specifically, how it grabs the fanfiction from Fanfiction.net. as of a day or two ago, fanfiction.net going through some changes that are preventing the app from grabbing the fics. Hopefully, it's not permanent and will be gone in a few days, but knowing 2020, it will be.). Anyway, I have no clue how to build it using, I'm guessing, Android Studio. I was hoping you could maybe tell me how to do so, including the steps for the Splunk Mint thingy in the README.

Please and thank you!

**Comment by andrewzeng** [comment]
This is pretty much a dead project, per the README it's just here because someone asked me to upload it, so I can't really provide any support for it. The project was originally loaded in Android Studio, yes. There are many alternatives to this app, so if you are solely looking to read stuff on ff.net I'd look elsewhere
